services:
  mysql:
    image: mysql:8.0.34
    environment:
      - 'MYSQL_DATABASE=recargapay'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
    volumes:
      - ./config/script:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - LOCALSTACK_DISABLE_SSL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/localstack:/etc/localstack/init/ready.d